"""update auths table

Revision ID: d915b91c47e3
Revises: 7826f15956d2
Create Date: 2025-05-28 10:06:30.108131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd915b91c47e3'
down_revision: Union[str, None] = '7826f15956d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auths', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
